# Generated by Django 5.1.7 on 2026-07-10 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('leaderName', models.CharField(max_length=150)),
                ('preferredDomain', models.CharField(max_length=150)),
                ('ideaDescription', models.TextField(blank=True)),
                ('availableDate', models.DateField()),
                ('slotTiming', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=20)),
                ('registrationFee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paymentDate', models.DateField(blank=True, null=True)),
                ('utrNumber', models.CharField(blank=True, max_length=100)),
                ('paymentScreenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('rulesAccepted', models.BooleanField(default=False)),
                ('mediaConsent', models.BooleanField(default=False)),
                ('technicalSkills', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150)),
                ('emailId', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('yearOfStudy', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=150)),
                ('isLeader', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
        ),
    ]
